version: '3.8'

services:
  client:
    build:
      context: . # Build context is the root of the repository
      dockerfile: ./client/Dockerfile # Point to the client's Dockerfile
    ports:
      - "8001:8001" # Map host port 8001 to container port 8001
    volumes:
      - ./client:/app # Mount the local client code into the container (useful for --reload)
    environment:
      # Variables specific to the client (can also use .env file)
      # EXAMPLE_CLIENT_VAR: ${EXAMPLE_CLIENT_VAR}
    env_file:
      - .env # Load environment variables from a .env file

  server:
    build:
      context: . # Build context is the root of the repository
      dockerfile: ./server/Dockerfile # Point to the server's Dockerfile
    ports:
      # Map host port (e.g., 3000) to container port (3000) if needed externally
      # If client and server only communicate within Docker network, host port mapping isn't strictly necessary
       - "3000:3000" # Assuming server runs on 3000 internally
    volumes:
      - ./server:/app # Mount the local server code into the container
      - /app/node_modules # Create an anonymous volume for node_modules (prevents host node_modules interfering)
    environment:
      # Variables specific to the server (can also use .env file)
      # EXAMPLE_SERVER_VAR: ${EXAMPLE_SERVER_VAR}
    env_file:
      - .env # Load environment variables from a .env file